fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: sqlx-data.json
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt.
        entry: cargo fmt
        language: system
        args: ["--", "--check"]
        types: [rust]
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false
      #- id: cargo-deny
      #  name: cargo deny check
      #  description: Lint your dependencies
      #  entry: cargo deny check
      #  language: system
      #  types: [rust]
      #  pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Lint your rust sources
        entry: cargo clippy
        language: system
        args: ["--", "--deny", "warnings"]
        types: [rust]
        pass_filenames: false
